import './globals.css'
import { Dosis } from 'next/font/google'
import Provider from './provider'
import { NavBar } from '@/components/Navbar/Navbar'
import { Footer } from '@/components/Footer/Footer'

const dosis = Dosis({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
interface RootLatoutProps {
  children: React.ReactNode
}

const RootLayout = (
  {
    children,
  }: RootLatoutProps
) => {
  return (
    <html lang="en">
      <body 
        className={dosis.className}
      >
        <Provider>
          <NavBar />
            {children}
          <Footer />
        </Provider>
      </body>
    </html>
  )
}

export default RootLayout;